version: '3.9'
services:
  core:
    restart: always
    build: ./vitamin_d_core
    ports:
      - 80:80

  scheduler:
    environment:
      - FLASK_ENV
      - FLASK_SECRET_KEY
      - MONGO_DB
      - MONGO_HOST
    restart: always
    build: ./vitamin_d_scheduler
        
  resource_user:
    environment:
      - FLASK_ENV
      - FLASK_SECRET_KEY
      - MONGO_DB
      - MONGO_HOST
    restart: always
    build: ./vitamin_d_resource_user

  resource_activity:
    environment:
      - MONGO_DB
      - MONGO_HOST
    restart: always
    build: ./vitamin_d_resource_activity
  mongo:
    image: mongo
    command: --quiet --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
 mongodb:
